### ISSUE TITLE
Bonsai asset creation has wrong filter for Windows 386

### ISSUE THREAD

**Issue by nixwiz** [sensu/sensu-pagerduty-handler#26]
The Bonsai asset definition for the Windows 386 build has amd64 for the arch.

```
spec:
  builds:
  - url: https://assets.bonsai.sensu.io/e6722787284bd20f68d0375ee927aa0ec5d2e57b/sensu-pagerduty-handler_1.3.2_windows_386.tar.gz
    sha512: 10eb353c624fa1853a5b6175366e6ae325315208b2289b1191629004737dbacbfc576f54b95a89560a5226e24aa0438458256b04ac1ffdc9876cf0afdf6441dd
    filters:
    - entity.system.os == 'windows'
    - entity.system.arch == 'amd64'
```
