### ISSUE TITLE
Recommend a namespaced --dedup-key-template for Pagerduty

### ISSUE THREAD

**Issue by calebhailey** [sensu/sensu-pagerduty-handler#31]
If you're integrating with Pagerduty from multiple namespaces, it may be prudent to use a "namespaced" Pagerduty `dedup_key` (see: https://support.pagerduty.com/docs/event-management#section-deduplicating-incidents). 

```yaml
type: Handler
api_version: core/v2
metadata:
  name: pagerduty
spec:
  command: >-
    sensu-pagerduty-handler
    --dedup-key-template "{{.Entity.Namespace}}-{{.Entity.Name}}-{{.Check.Name}}"
    --summary-template "{{.Entity.Name}}/{{.Check.Name}}: {{.Check.Output}}"
    --status-map "{\"info\":[0],\"warning\": [1],\"critical\": [2],\"error\": [3,127]}"
  filters:
  - is_incident
  - not_silenced
  runtime_assets:
  - sensu/sensu-pagerduty-handler:2.0.1
  secrets:
  - name: PAGERDUTY_TOKEN
    secret: pagerduty_token
  timeout: 0
  type: pipe
```
