### ISSUE TITLE
Add support for basic contact routing

### ISSUE THREAD

**Issue by calebhailey** [sensu/sensu-pagerduty-handler#46]
Add a new `--contact-routing` flag

* Looks for and merges the entity, check, and/or event `contacts` annotation.

  The `contacts` annotation(s) should be formatted as a comma-separate list of contact names.

  ```yaml
  annotations:
    contacts: "team_a,team_b"
  ```

  _NOTE: Contact names may contain only alpha-numeric characters and underscore (`_`)._

* The `--contact-routing` flag should cause the handler to log the merged list of contacts

  Example:

  ```
  Pagerduty contact routing is enabled (contacts: team_a, team_b)
  ```

* Execute `manageIncident()` function once per contact

  Lookup environment variable matching `fmt.Sprintf("PAGERDUTY_TOKEN_%s", strings.ToUpper(contact))` (or similar).

  Notes on environment variable lookups:

  * TBD if `--contact-routing` could be used with the existing `--team` and `--team-suffix` flags for looking up contact environment variables.
  * TBD if environment variables should use a configurable or hardcoded _prefix_ (e.g. `PAGERDUTY_TOKEN_`) or suffix (see above RE: reusing existing `--team-suffix` flag). 
  * Perhaps a `--contact-prefix` flag would be best so it doesn't conflict with existing functionality? 

  If the contact environment is found, perform the `manageIncident()` function.

  If the contact environment variable is not found, log an warning (e.g. `WARNING: skipping contact: "team-a" (no environment variable found for "PAGERDUTY_TOKEN_TEAM_A")\n`).

  If at least one matching contact environment variable is found and `manageIncident()` returns no errors, the handler should exit with status 0.

Example pipeline configuration: 

```yaml
---
api_version: core/v2
type: Pipeline
metadata:
  name: pagerduty
spec:
  workflows:
    - name: pagerduty
      filters:
        - api_version: core/v2
          type: EventFilter
          name: is_incident
        - api_version: core/v2
          type: EventFilter
          name: not_silenced
      handler:
        api_version: core/v2
        type: Handler
        name: pagerduty
---
# Requires PAGERDUTY_TOKEN environment variable or secret
api_version: core/v2
type: Handler
metadata:
  name: pagerduty
spec:
  type: pipe
  command: >-
    sensu-pagerduty-handler
    --contact-routing
    --contact-prefix "PAGERDUTY_TOKEN_"
    --dedup-key-template "{{.Entity.Namespace}}-{{.Entity.Name}}-{{.Check.Name}}"
    --status-map "{\"info\":[0],\"warning\": [1],\"critical\": [2],\"error\": [3,127]}"
    --summary-template "[{{.Entity.Namespace}}] {{.Entity.Name}}/{{.Check.Name}}: {{.Check.State}}"
    --details-template ""{{ .Check.Name }} is {{ .Check.State }} on {{ .Entity.Name }} (namespace: {{ .Entity.Namespace }})\n\n{{ or (index .Annotations \"sensu.io/notifications/critical\") (index .Annotations \"sensu.io/notifications/warning\") .Check.Output }}""
  timeout: 10
  filters: []
  runtime_assets:
    - sensu/sensu-pagerduty-handler
  env_vars: []
  secrets:
    - name: PAGERDUTY_TOKEN_TEAM_A
      secret: pagerduty_team_a
    - name: PAGERDUTY_TOKEN_TEAM_B
      secret: pagerduty_team_B
```

Example agent config: 

```yaml
---
# example agent.yml
name: i-424242
labels: {}
annotations:
  contacts: "team_a,team_b"
```

Example check config: 

```yaml
---
api_version: core/v2
type: CheckConfig
metadata:
  name: example-check
  annotations:
    contacts: "team_c"
spec:
  ...: ...
```
